services:
  frontend:
    build: ./frontend
    ports: 
      - 8080:5173
    environment:
      - AUTH_SECRET=${AUTH_JS_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  gitter:
    build: ./gitter
    ports:
      - 8081:8000
    volumes:
      - ./gitter:/gitter
      - /gitter/__pycache__
